#!/bin/bash
# utility to wrap the package for distribution    (c) Frank Lübeck

echo " Are versions and dates updated? (dev/setversiondate ...)"
read -n 1 -p "-->" start
echo
if [ $start'X' != 'yX' ]; then
  echo Ok, please adjust and try again.
  exit 2
fi

HERE=`pwd`
DIRNAM=EDIM-`cat VERSION`
rm -rf buildtmp
mkdir buildtmp
cd buildtmp
# clone and build documentation
git clone $HERE ./$DIRNAM
cd $DIRNAM
gap makedocrel.g
rm -rf .git dev doc/*.aux doc/*.log doc/*.blg doc/*.xsl doc/*.ilg doc/*.brf doc/*.out

# now pack archive
cd ..
tar cvf $DIRNAM.tar $DIRNAM
gzip -9 $DIRNAM.tar
mv $DIRNAM.tar.gz ..
cd ..
rm -rf buildtmp

echo "If content with the archive $DIRNAM.tar.gz use"
echo "            repack.py $DIRNAM.tar.gz"
echo "to produce the other archive formats."
echo 
echo "Then check dev/index.html and use"
echo "            dev/copytoweb"

