#!/bin/sh -x 

mv mathml.css XXXXX

rm -f *.css *.js *.aux *.lab *.log *.dvi *.ps *.pdf *.bbl *.ilg *.ind *.idx *.out *.html *.tex *.pnr *.txt *.blg *.toc *.six *.brf chap*_mml.xml *~

mv XXXXX mathml.css

